[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
name = "datafinder"
version = "0.0.1"

[tool.setuptools]
    packages = ['datafinder','datafinder_duckdb','example','example_kdb','example_duckdb','model','calc']
    package-dir = { "calc" = "calc/src", "datafinder" = "datafinder" }

[project]
name = "datafinder"
version = "0.0.1"
authors = [
  { name="Jackie Haynes" },
]
description = "Generated data finders"
readme = "README.md"
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src", "calc/src", "datafinder", "example_ibis"
]